from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Heading = QtWidgets.QLabel(self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(290, 0, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setObjectName("Heading")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.File_link = QtWidgets.QLineEdit(self.centralwidget)
        self.File_link.setGeometry(QtCore.QRect(440, 60, 431, 21))
        self.File_link.setObjectName("File_link")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.File_location = QtWidgets.QLineEdit(self.centralwidget)
        self.File_location.setGeometry(QtCore.QRect(440, 90, 341, 21))
        self.File_location.setObjectName("File_location")
        self.Browse_Files = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_Files.setGeometry(QtCore.QRect(780, 90, 91, 21))
        self.Browse_Files.clicked.connect(self.browse_file)

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Browse_Files.setFont(font)
        self.Browse_Files.setObjectName("Browse_Files")
        self.Start_Download = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Download.setGeometry(QtCore.QRect(340, 120, 201, 28))
        self.Start_Download.clicked.connect( self.start_download )

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Download.setFont(font)
        self.Start_Download.setObjectName("Start_Download")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 520, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 520, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 520, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(9, 156, 871, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # return([file_link,file_location])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Heading.setText(_translate("MainWindow", "File Downloader "))
        self.label.setText(_translate("MainWindow", "Enter the URL of file you want to download ->"))
        self.File_link.setText(_translate("MainWindow", "Please enter the Link"))
        self.label_2.setText(_translate("MainWindow", "Enter the location of your file to be saved ->"))
        self.File_location.setText(_translate("MainWindow", "Enter Location You want to save "))
        self.Browse_Files.setText(_translate("MainWindow", "Browse"))
        self.Start_Download.setText(_translate("MainWindow", "Start The Download "))
        self.pushButton.setText(_translate("MainWindow", "Pause All"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel All"))
        self.pushButton_3.setText(_translate("MainWindow", "Resume All"))

    def start_download(self):
        file_link = self.File_link.text()
        file_location = self.File_location.text()
        import downloading as dow
        dow.download(file_link,file_location)

    def browse_file(self):
        self.open_dialog_box()
    def open_dialog_box(self):
        file_location = QFileDialog.getSaveFileName()
        self.File_location.setText(file_location[0])



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
